nodeLinker: node-modules

# Let the cache lives in the current project directory so that it can be pruned
# when deps are changed (allows smarter caching on CI for example)
enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
